version: "3"

services:
  mariadb:
    image: mariadb:10.2
    restart: 'always'
    hostname: mariadb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: "classicmodels"
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./script/sql/001_schema.sql:/docker-entrypoint-initdb.d/001_schema.sql"
    ports:
      - "3306:3306"